name: Feature Request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the request
      description: What do you want to be added to the bot?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is (if applicable). Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
